name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Setup Terraform for generate providers
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Generate providers
        env:
          MACKEREL_API_KEY: stub
        run: pnpm cdktf provider get

      - name: Check formatting
        run: pnpm run lint

      - name: Check types
        run: pnpm run type-check

      - name: Run tests
        run: pnpm run test

  plan:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Setup Terraform for generate providers
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3"

      - name: Generate providers
        env:
          MACKEREL_API_KEY: stub
        run: pnpm cdktf provider get

      - name: Plan AWS
        uses: hashicorp/terraform-cdk-action@v11
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: aws
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: "1.11.3"

      - name: Plan Cloudflare
        uses: hashicorp/terraform-cdk-action@v11
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: cloudflare
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: "1.11.3"

      - name: Plan Mackerel
        uses: hashicorp/terraform-cdk-action@v11
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: mackerel
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: "1.11.3"

      - name: Plan Terraform Cloud
        uses: hashicorp/terraform-cdk-action@v11
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: terraform-cloud
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: "1.11.3"
